name:                generic-validated
version:             0.1.0.0
description:         See README.md

dependencies:
- aeson
- barbies
- base
- generic-deriving
- unordered-containers
- validation

- generic-lens
- QuickCheck

library:
  source-dirs: src
